export const products = [
  {
    id: '1f4b2e3c-a68d-4c1f-8a4e-0d315a983b6c',
    product_name: 'E-commerce Platform',
    status: 'in developement',
    backLog_items: [
      {
        id: 1,
        userStory_name: 'User Registration',
        priority: 'High',
        estimatedEffort: 5,
        description:
          'Allow users to create accounts and store their information.',
        userStory:
          'As a user, I want to user registration so that I can achieve my goals.',
        userStory_id: '8a09830f-8e46-438c-b4cc-7432aa8de12b',
        writtenByTeamMember_id: 'ab8ac605-7ac5-49fd-a0d9-4b8ce11f7da5',
      },
      {
        id: 2,
        userStory_name: 'Product Catalog',
        priority: 'High',
        estimatedEffort: 8,
        description: 'Display products with details, images, and prices.',
        userStory:
          "As a customer, I want to product catalog so that I can find what I'm looking for.",
        userStory_id: '873a5f7a-cd47-4102-ad73-84f51ef934ed',
        writtenByTeamMember_id: 'ab8ac605-7ac5-49fd-a0d9-4b8ce11f7da5',
      },
      {
        id: 3,
        userStory_name: 'Shopping Cart',
        priority: 'Medium',
        estimatedEffort: 3,
        description:
          'Enable users to add products to a cart for later purchase.',
        userStory:
          'As a customer, I want to shopping cart so that I can manage my purchases.',
        userStory_id: 'bd37e325-52f9-48f4-ae61-5d6c107e161e',
        writtenByTeamMember_id: 'b7c9a99a-a2a8-44dd-b986-d04f69b06efd',
      },
      {
        id: 4,
        userStory_name: 'Checkout Process',
        priority: 'High',
        estimatedEffort: 10,
        description: 'Implement a secure and user-friendly checkout flow.',
        userStory:
          'As a customer, I want to payment gateway integration so that I can purchase products easily.',
        userStory_id: '9b950fa9-27a1-4f26-b338-a817abf3e3b3',
        writtenByTeamMember_id: '36f1b9b4-85fe-4193-9d7c-3fe7bdbc1194',
      },
      {
        id: 5,
        userStory_name: 'Order Tracking',
        priority: 'Medium',
        estimatedEffort: 4,
        description: 'Allow users to track the status of their orders.',
        userStory:
          'As a customer, I want to order tracking so that I can manage my purchases.',
        userStory_id: 'ccd29397-8de7-4a5a-beba-54e5fc6dabba',
        writtenByTeamMember_id: '12b66790-3975-4888-853c-d7f3f8da79a4',
      },
    ],
  },
  {
    id: 'a7c5d8e4-25b4-4e35-b37b-d1f8e0092f0e',
    product_name: 'Project Management Tool',
    status: 'in production',
    backLog_items: [
      {
        id: 1,
        userStory_name: 'Task Creation and Assignment',
        priority: 'High',
        estimatedEffort: 6,
        description:
          'Allow users to create tasks and assign them to team members.',
        user_story:
          'As a user, I want to mobile app development so that I can achieve my goals.',
        userStory_id: '9a138bf7-0cdb-4e7d-92fe-f14c3897140b',
        writtenByTeamMember_id: 'b7c9a99a-a2a8-44dd-b986-d04f69b06efd',
      },
      {
        id: 2,
        userStory_name: 'Kanban Board',
        priority: 'High',
        estimatedEffort: 8,
        description: 'Visualize workflow with a customizable Kanban board.',
        userStory_id: '755d041f-a4fb-48e2-8f14-315a51b58f9a',
        writtenByTeamMember_id: null,
      },
      {
        id: 3,
        userStory_name: 'Gantt Chart',
        priority: 'Medium',
        estimatedEffort: 5,
        description:
          'Provide a timeline view of project tasks and dependencies.',
        userStory_id: '3207d0b9-730d-4282-b09c-8c42c55b918f',
        writtenByTeamMember_id: null,
      },
      {
        id: 4,
        userStory_name: 'Time Tracking',
        priority: 'Low',
        estimatedEffort: 3,
        description: 'Enable users to track time spent on tasks.',
        userStory_id: '24054d06-3f60-4f1e-ba7c-644ee8c566a3',
        writtenByTeamMember_id: null,
      },
      {
        id: 5,
        userStory_name: 'Reporting and Analytics',
        priority: 'Medium',
        estimatedEffort: 7,
        description:
          'Generate reports on project progress and team performance.',
        userStory_id: '41a39e0f-7726-4499-b649-7e60a928b99d',
        writtenByTeamMember_id: null,
      },
      {
        id: 6,
        userStory_name: 'Social Media Integration',
        priority: 'Medium',
        estimatedEffort: 3,
        description: '',
        user_story:
          'As a user, I want to mobile app development so that I can achieve my goals.',
        userStory_id: 'a311cd75-8722-487c-9ad4-7b6395a5ad41',
        writtenByTeamMember_id: 'b7c9a99a-a2a8-44dd-b986-d04f69b06efd',
      },
      {
        id: 7,
        userStory_name: 'Mobile App Development',
        priority: 'High',
        estimatedEffort: 10,
        description: 'Implement live video streaming functionality.',
        userStory_id: '9a138bf7-0cdb-4e7d-92fe-f14c3897140b',
        writtenByTeamMember_id: null,
      },
    ],
  },
  {
    id: 'e072f3a1-c28c-40e5-a7de-0b97a2e416f7',
    product_name: 'Social Media App',
    status: 'in developement',
    backLog_items: [
      {
        id: 1,
        userStory_name: 'User Profiles',
        priority: 'High',
        estimatedEffort: 5,
        description: 'Allow users to create profiles and share information.',
        userStory_id: 'f6ae82a0-6588-4675-b209-742da8cc4f71',
        writtenByTeamMember_id: 'ab8ac605-7ac5-49fd-a0d9-4b8ce11f7da5',
      },
      {
        id: 2,
        userStory_name: 'News Feed',
        priority: 'High',
        estimatedEffort: 7,
        description: 'Display posts from friends and followed accounts.',
        userStory_id: '62f05723-171c-4df2-9067-e332f94dba43',
        writtenByTeamMember_id: null,
      },
      {
        id: 3,
        userStory_name: 'Messaging',
        priority: 'Medium',
        estimatedEffort: 6,
        description: 'Enable users to send private messages to each other.',
        userStory_id: '277a9d28-9ef3-403e-8f89-aae931492c29',
        writtenByTeamMember_id: null,
      },
      {
        id: 4,
        userStory_name: 'Groups and Communities',
        priority: 'Low',
        estimatedEffort: 4,
        description:
          'Allow users to create and join groups based on interests.',
        userStory_id: 'fb65e361-032f-470a-8f3c-e9390861b5a5',
        writtenByTeamMember_id: null,
      },
      {
        id: 5,
        userStory_name: 'Live Streaming',
        priority: 'High',
        estimatedEffort: 10,
        description: 'Implement live video streaming functionality.',
        userStory_id: '538d899e-2673-4b53-b50c-5ae065d6ba1c',
        writtenByTeamMember_id: null,
      },
    ],
  },
];
